import Head from 'next/head'
import { Inter } from '@next/font/google'
import Main from '@/components/main/Main'
import Brands from '@/components/brands/Brands'
import VisualChoosing from '@/components/visualChoosing/VisualChoosing'
import AboutUs from '@/components/aboutUs/AboutUs'
import Projects from '@/components/projects/Projects'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <Brands />
      <VisualChoosing />
      <AboutUs />
      <Projects />
    </>
  )
}
